repology_url = "https://repology.org"

# If you do care only about some repositories, you can whitelist them here and repolocli won't print information for
# these repositories.
whitelist = [
    "Debian Stable" # sorry Debianers!
]

# If you do not care about some repositories, you can blacklist them here and repolocli won't print information for
# these repositories.
blacklist = [
    "Arch", # sorry Archers!
    "scientific_7x",
]
