use clap::{Arg, Command};

pub fn build_cli() -> Command {
    Command::new("repolocli")
        .version("0.1")
        .author("Matthias Beyer <mail@beyermatthias.de>")
        .about("Query repology.org and postprocess its output")

        .arg(Arg::new("config")
            .long("config")
            .value_name("PATH")
            .required(false)
            .num_args(..)
            .help("Override default configuration file path")

        )

        .arg(Arg::new("verbose")
                 .long("verbose")
                 .short('v')
                 .action(clap::ArgAction::Count)
                 .help("Increase verbosity. Default = Info, -v = Debug, -vv = Trace")
        )

        .arg(Arg::new("quiet")
            .long("quiet")
            .short('q')
            .action(clap::ArgAction::Count)
            .help("Decrease verbosity. Default = Info, -q = Warn, -qq = Error")
        )

        .arg(Arg::new("output")
            .long("output")
            .short('o')
            .required(false)
            .num_args(1)
            .value_parser(["table", "json", "lines"])
            .default_value("lines")
            .help("Output format")
        )

        .arg(Arg::new("input_stdin")
            .long("stdin")
            .short('I')
            .action(clap::ArgAction::SetTrue)
            .help("Read data (JSON) from stdin.")
        )

        .subcommand(Command::new("project")
            .arg(Arg::new("project_name")
                .index(1)
                .required(true)
                .num_args(1)
                .help("Query data about a project")
            )

            .arg(Arg::new("sort-version")
                .long("sort-version")
                .action(clap::ArgAction::SetTrue)
                .help("Sort output by version")
                .conflicts_with("sort-repo")
            )
            .arg(Arg::new("sort-repo")
                .long("sort-repo")
                .action(clap::ArgAction::SetTrue)
                .help("Sort output by repository")
                .conflicts_with("sort-version")
            )
            .arg(Arg::new("latest")
                .long("latest")
                .action(clap::ArgAction::SetTrue)
                .help("Try to find the lastest version (version is string-compared if not used with --semver)")
                .conflicts_with("sort-version")
                .conflicts_with("sort-repo")
            )
            .arg(Arg::new("semver")
                .long("semver")
                .action(clap::ArgAction::SetTrue)
                .requires("latest")
                .help("Try to find latest version using semver. If semver could not be parsed, equality is assumed, which might yield bogus results.")
            )
        )

        .subcommand(Command::new("problems")
            .arg(Arg::new("repo")
                .short('r')
                .long("repo")
                .alias("repository")
                .required(true)
                .num_args(1)
                .help("The repository to get problems for (required)")
            )

            .arg(Arg::new("maintainer")
                .short('m')
                .long("maintainer")
                .alias("maint")
                .required(false)
                .num_args(1)
                .help("Filter problems by maintainer (uses maintainer-specific API)")
            )


            .arg(Arg::new("sort-maintainer")
                .long("sort-maintainer")
                .action(clap::ArgAction::SetTrue)
                .help("Sort output by maintainer")
                .conflicts_with("sort-repo")
            )
            .arg(Arg::new("sort-repo")
                .long("sort-repo")
                .action(clap::ArgAction::SetTrue)
                .help("Sort output by repository")
                .conflicts_with("sort-maintainer")
            )
        )

        .after_help(r#"
        repolocli can read data from stdin, if you want to postprocess repology.org data you already
        fetched from repology.org/api/v1 via curl (or some other method).
        In this case, repolocli is only a easier-to-use 'jq' (if you don't know jq, look it up NOW!).
        "#)
}
